//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/scg/connectors/black24.yaml
// auto-generated by PinoutLogic.java based on config/boards/scg/connectors/grey24.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::E13, // Lowside 1 (Black A1)
	Gpio::E12, // Lowside 2 (Black A2)
	Gpio::D14, // Lowside 3 (Black A3)
	Gpio::D15, // Lowside 4 (Black A4)
	Gpio::E9, // Lowside 5 (Black A5)
	Gpio::E8, // Lowide 6 (Black A6)
	Gpio::E15, // Lowside 7 (Black A7)
	Gpio::E14, // Lowside 8 (Black A8)
	Gpio::E10, // Lowside 9 (Black C1)
	Gpio::E11, // Lowside 10 (Black C2)
	Gpio::C7, // Lowside 11 (Black C3)
	Gpio::C6, // Lowside 12 (Black C4)
	Gpio::E2, // Lowside 13 0.7A (Black C5)
	Gpio::E5, // Tachometer (Black C6)
	Gpio::D11, // Highside 1 (Black B1)
	Gpio::D10, // Highside 2 (Black B2)
	Gpio::D8, // Highside 3 (Black B3)
	Gpio::D9, // Highside 4 (Black B4)
	Gpio::D12, // Highside 5 (Black B5)
	Gpio::D13, // Highside 6 (Black B6)
	Gpio::B15, // Highside 7 (Black B7)
	Gpio::B14, // Highside 8 (Black B8)
// "Lowside 1 (Black A1)",
// "Lowside 2 (Black A2)",
// "Lowside 3 (Black A3)",
// "Lowside 4 (Black A4)",
// "Lowside 5 (Black A5)",
// "Lowide 6 (Black A6)",
// "Lowside 7 (Black A7)",
// "Lowside 8 (Black A8)",
// "Lowside 9 (Black C1)",
// "Lowside 10 (Black C2)",
// "Lowside 11 (Black C3)",
// "Lowside 12 (Black C4)",
// "Lowside 13 0.7A (Black C5)",
// "Tachometer (Black C6)",
// "Highside 1 (Black B1)",
// "Highside 2 (Black B2)",
// "Highside 3 (Black B3)",
// "Highside 4 (Black B4)",
// "Highside 5 (Black B5)",
// "Highside 6 (Black B6)",
// "Highside 7 (Black B7)",
// "Highside 8 (Black B8)",
}
