//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/scg/connectors/black24.yaml
// auto-generated by PinoutLogic.java based on config/boards/scg/connectors/grey24.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A1: return "Analog Volt 1 (Grey B3)";
		case Gpio::A2: return "Analog Temp 1 (Grey C4)";
		case Gpio::A3: return "Analog Temp 2 (Grey C5)";
		case Gpio::A4: return "Analog Volt 3 (Grey B5)";
		case Gpio::B0: return "Analog Volt 2 (Grey C3)";
		case Gpio::B14: return "Highside 8 (Black B8)";
		case Gpio::B15: return "Highside 7 (Black B7)";
		case Gpio::C13: return "Digital 1 or VR/Hall (Grey B7, A6/B6)";
		case Gpio::C6: return "Lowside 12 (Black C4)";
		case Gpio::C7: return "Lowside 11 (Black C3)";
		case Gpio::D10: return "Highside 2 (Black B2)";
		case Gpio::D11: return "Highside 1 (Black B1)";
		case Gpio::D12: return "Highside 5 (Black B5)";
		case Gpio::D13: return "Highside 6 (Black B6)";
		case Gpio::D14: return "Lowside 3 (Black A3)";
		case Gpio::D15: return "Lowside 4 (Black A4)";
		case Gpio::D8: return "Highside 3 (Black B3)";
		case Gpio::D9: return "Highside 4 (Black B4)";
		case Gpio::E1: return "Clutch (Grey B4)";
		case Gpio::E10: return "Lowside 9 (Black C1)";
		case Gpio::E11: return "Lowside 10 (Black C2)";
		case Gpio::E12: return "Lowside 2 (Black A2)";
		case Gpio::E13: return "Lowside 1 (Black A1)";
		case Gpio::E14: return "Lowside 8 (Black A8)";
		case Gpio::E15: return "Lowside 7 (Black A7)";
		case Gpio::E2: return "Lowside 13 0.7A (Black C5)";
		case Gpio::E5: return "Tachometer (Black C6)";
		case Gpio::E6: return "Digital 1 or VR/Hall (Grey A7, Grey A5/C6)";
		case Gpio::E8: return "Lowide 6 (Black A6)";
		case Gpio::E9: return "Lowside 5 (Black A5)";
		default: return nullptr;
	}
	return nullptr;
}
