//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/scg/connectors/black24.yaml
// auto-generated by PinoutLogic.java based on config/boards/scg/connectors/grey24.yaml
#pragma once

#define PIN_1 E13
#define PIN_2 E12
#define PIN_3 D14
#define PIN_4 D15
#define PIN_5 E9
#define PIN_6 E8
#define PIN_7 E15
#define PIN_8 E14
#define PIN_9 D11
#define PIN_10 D10
#define PIN_11 D8
#define PIN_12 D9
#define PIN_13 D12
#define PIN_14 D13
#define PIN_15 B15
#define PIN_16 B14
#define PIN_17 E10
#define PIN_18 E11
#define PIN_19 C7
#define PIN_20 C6
#define PIN_21 E2
#define PIN_22 E5
#define PIN_7_event_inputs E6
#define PIN_7_switch_inputs E6
#define PIN_11_switch_inputs A1
#define PIN_11_analog_inputs EFI_ADC_1
#define PIN_12_event_inputs E1
#define PIN_12_switch_inputs E1
#define PIN_13_switch_inputs A4
#define PIN_13_analog_inputs EFI_ADC_4
#define PIN_15_event_inputs C13
#define PIN_15_switch_inputs C13
#define PIN_19_switch_inputs B0
#define PIN_19_analog_inputs EFI_ADC_10
#define PIN_20_switch_inputs A2
#define PIN_20_analog_inputs EFI_ADC_2
#define PIN_21_switch_inputs A3
#define PIN_21_analog_inputs EFI_ADC_3
